# Custom Language File for Launcher Customizer

[ejs.app]
title = "ONYX Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/ONYX-Minestudio/ONYX-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/ONYX-Minestudio/ONYX-Launcher"
supportLink = "https://github.com/ONYX-Minestudio/ONYX-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur ONYX Launcher"
welcomeDescription = "Onyx launcher se compose d'actuellement que d'un serveur qui se nomme NP Empire"
welcomeDescCTA = "Vous n’êtes qu’à quelques clics de NP Empire."
