# Custom Language File for Launcher Customizer

[ejs.app]
title = "Onyx Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/ONYX-Minestudio/ONYX-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/ONYX-Minestudio/ONYX-Launcher"
supportLink = "https://github.com/ONYX-Minestudio/ONYX-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue"
